### ISSUE TITLE
Publish 3.2.2 to npm

### ISSUE THREAD

**Issue by jlamendo** [vivaxy/here#18]
There is a security vulnerability in version 3.2.0, the latest version available on npm. Please publish 3.2.2 to npm to allow users to access the secure version without having to pull directly from git. Thank you!

References:

https://hackerone.com/reports/296254

**Comment by vivaxy** [comment]
@jlamendo `serve-here@3.2.0` is already deprecated. The new package name is `@vivaxy/here`.

![image](https://user-images.githubusercontent.com/4216856/34856058-167c539c-f77e-11e7-8e7f-57b2da362869.png)
