### ISSUE TITLE
添加gzip支持

### ISSUE THREAD

**Issue by ygtzz** [vivaxy/here#19]
可否添加gzip支持，方便进行性能测试

**Comment by vivaxy** [comment]
@ygtzz 麻烦详细说说。
1. 需求的背景
2. 预期的使用方式
3. 示例代码

**Comment by ygtzz** [comment]
1. 需求背景
项目打包好的文件需要进行性能调优，用chrome的perfermance观察加载时间等指标。不方便直接部署到服务器上，想在本地打包好的文件，进行基本的性能测试，查看不同打包方式对性能的影响。不开启gzip无法模拟真实环境，文件体积影响加载时间。
2. 预期是使用方式
能用命令行直接开启最好 here --gzip 或 here -G
用代码注入的方式也能接受
3. 示例代码
只是加载文件，不涉及代码
